export const SET_ARTICLE = 'SET_ARTICLE_ACTION';
export const SET_ARTICLES_LIST = 'SET_ARTICLES_LIST_ACTION';
export const SET_ARTICLES_COUNT = 'SET_ARTICLES_COUNT';
export const SET_CONTENT_LOADING = 'SET_CONTENT_LOADING_ACTION';
export const SET_ERROR = 'SET_ERROR';
export const SET_USER = 'SET_USER';